base_settings:
  audio_codec: nvidia/nemo-nano-codec-22khz-0.6kbps-12.5fps
  num_readers: 8
  qsize: 100000
  OUT_DIR: shards 
  gzip_level: 1
  buffer_size: 16777216
  lines_per_file: 50000
  load_dataset_num_proc: 20

save_settings:
  local: catalan_tts_dataset                   # dataset dir
  hf_upload: xaviviro/cv_23_ca_distilled_nano_codec  # ‚Üê CHANGE THIS to your HF repo

hf_datasets:

  - name: xaviviro/cv_23_ca_distilled
    sub_name: alacanti
    split: train
    text_column_name: text
    audio_column_name: audio
    speaker_column_name: null
    add_constant:
      - key: speaker
        value: alacanti
      - key: lang
        value: ca

  - name: xaviviro/cv_23_ca_distilled
    sub_name: balearic
    split: train
    text_column_name: text
    audio_column_name: audio
    speaker_column_name: null
    add_constant:
      - key: speaker
        value: balearic
      - key: lang
        value: ca

  - name: xaviviro/cv_23_ca_distilled
    sub_name: central
    split: train
    text_column_name: text
    audio_column_name: audio
    speaker_column_name: null
    add_constant:
      - key: speaker
        value: central
      - key: lang
        value: ca

  - name: xaviviro/cv_23_ca_distilled
    sub_name: northwestern
    split: train
    text_column_name: text
    audio_column_name: audio
    speaker_column_name: null
    add_constant:
      - key: speaker
        value: northwestern
      - key: lang
        value: ca

  - name: xaviviro/cv_23_ca_distilled
    sub_name: septentrional
    split: train
    text_column_name: text
    audio_column_name: audio
    speaker_column_name: null
    add_constant:
      - key: speaker
        value: septentrional
      - key: lang
        value: ca


  - name: xaviviro/cv_23_ca_distilled
    sub_name: tortosi
    split: train
    text_column_name: text
    audio_column_name: audio
    speaker_column_name: null
    add_constant:
      - key: speaker
        value: tortosi
      - key: lang
        value: ca

  - name: xaviviro/cv_23_ca_distilled
    sub_name: valencian
    split: train
    text_column_name: text
    audio_column_name: audio
    speaker_column_name: null
    add_constant:
      - key: speaker
        value: valencian
      - key: lang
        value: ca